spring.application.name=DATN


spring.jpa.hibernate.ddl-auto= update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/DATN}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql=true



# SMTP Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

# Additional Mail Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

server.port=${SERVER_PORT:9091}
jwt.signerKey=${JWT_SIGNER_KEY:}
jwt.valid-duration=${JWT_VALID_DURATION:3600}
jwt.refreshable-duration=${JWT_REFRESHABLE_DURATION:36000}
spring.main.allow-bean-definition-overriding=true
